import {voiceSession} from '@/lib/edu/voice-context';
import {interviewSession,interviewTypes,interviewDifficulties,interviewLanguages} from '@/lib/edu/interview-context';
import {config,configured,guestConfigured,guestIdentity,issueGuestSession,supa,cookie,identity,rateLimit,stateSchema,tutor,grade,analyzeResume} from '@/lib/edu/server';
import {env} from 'cloudflare:workers';
import {questions} from '@/lib/edu/content';
import {z} from 'zod';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200,headers:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
async function handle(req:Request,{params}:{params:Promise<{path:string[]}>}){const path=(await params).path.join('/');try{
if(path==='config')return json({demo:false,live:!!(config('GEMINI_API_KEY')||config('ASSEMBLYAI_API_KEY')),assembly:!!config('ASSEMBLYAI_API_KEY'),auth:configured(),agent:!!config('ASSEMBLYAI_API_KEY'),guestSiteKey:guestConfigured()&&!configured()?config('TURNSTILE_SITE_KEY'):null});
if(req.method!=='GET'){const origin=req.headers.get('origin');const allowedOrigin=config('FRONTEND_ORIGIN')||new URL(req.url).origin;if(origin&&origin!==allowedOrigin)return json({error:'Cross-origin requests are not permitted.'},403);if(Number(req.headers.get('content-length')||0)>8*1024*1024)return json({error:'Request is too large.'},413);}
if(path==='guest/status')return json({active:!!await guestIdentity(req)});
if(path==='guest/session'&&req.method==='POST'){
  if(!guestConfigured()||configured())return json({error:'Guest access is not configured.'},503);
  const binding=(env as unknown as {GLOBAL_AI_LIMITER?:{limit:(input:{key:string})=>Promise<{success:boolean}>}}).GLOBAL_AI_LIMITER;
  if(!binding)return json({error:'Guest access limit is not configured.'},503);
  if(!(await binding.limit({key:'guest-issuance'})).success)return json({error:'Please try again in a minute.'},429);
  const {token}=z.object({token:z.string().min(1).max(2048)}).parse(await req.json());
  const verify=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:config('TURNSTILE_SECRET_KEY'),response:token}),signal:AbortSignal.timeout(10000)});
  if(!verify.ok)return json({error:'Verification is temporarily unavailable.'},502);
  const result=await verify.json() as {success:boolean;hostname?:string};
  if(!result.success||result.hostname!==new URL(config('FRONTEND_ORIGIN')).hostname)return json({error:'Human verification failed. Please try again.'},403);
  return json({success:true},200,{'Set-Cookie':`edu_guest=${await issueGuestSession()}; HttpOnly; Secure; SameSite=Lax; Path=/api; Max-Age=86400`});
}
if(path==='auth/logout')return json({success:true},200,{'Set-Cookie':'edu_access=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'});
if(path==='auth/login'||path==='auth/signup'){if(!configured())return json({error:'Accounts are not configured yet. Contact the site administrator.'},503);if(!rateLimit('auth:'+req.headers.get('cf-connecting-ip')))return json({error:'Too many attempts. Try again in a minute.'},429);const b=z.object({email:z.string().email().max(254),password:z.string().min(8).max(128)}).parse(await req.json());const d=await supa(path.endsWith('signup')?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(b)});const token=d.access_token||d.session?.access_token;if(!token)return json({confirmation:true,message:'Check your email to confirm your account, then sign in.'});return json({success:true},200,{'Set-Cookie':`edu_access=${token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=3600`});}
const user=await identity(req);
if(path==='state'){if(!configured())return json({local:true});if(!user)return json({error:'Sign in to load your saved learning profile.'},401);if(req.method==='GET'){const rows=await supa('/rest/v1/profiles?select=data&user_id=eq.'+encodeURIComponent(user.id),{},user.token);return json({state:rows[0]?.data||null})}const data=stateSchema.parse(await req.json());await supa('/rest/v1/profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({user_id:user.id,data,updated_at:new Date().toISOString()})},user.token);return json({success:true});}
// Paid AI endpoints require verified identity whenever a provider key is configured.
const paid=config('GEMINI_API_KEY')||config('ASSEMBLYAI_API_KEY');if(paid&&!user)return json({error:'Complete the human verification to use live AI.'},401);
if(paid&&user?.id.startsWith('guest:')){const bindings=env as unknown as {AI_RATE_LIMITER?:{limit:(input:{key:string})=>Promise<{success:boolean}>};GLOBAL_AI_LIMITER?:{limit:(input:{key:string})=>Promise<{success:boolean}>}};if(!bindings.AI_RATE_LIMITER||!bindings.GLOBAL_AI_LIMITER)return json({error:'Guest usage limits are not configured.'},503);const [individual,global]=await Promise.all([bindings.AI_RATE_LIMITER.limit({key:user.id}),bindings.GLOBAL_AI_LIMITER.limit({key:'paid-ai'})]);if(!individual.success||!global.success)return json({error:'Live AI usage limit reached. Please try again later.'},429);}
if(!rateLimit(user?.id||req.headers.get('cf-connecting-ip')||'anonymous'))return json({error:'Please wait a minute before trying again.'},429);
if(path==='voice/message')return json(await tutor(await req.json()));
if(path==='resume/analyze')return json(await analyzeResume(await req.json()));
if(path==='quiz/answer')return json(await grade(await req.json()));
if(path==='quiz/start'){const b=z.object({subject:z.string(),topic:z.string(),count:z.number().int().min(1).max(10)}).parse(await req.json());return json({questions:questions.filter(q=>q.subject===b.subject&&q.topic===b.topic).slice(0,b.count).map(({answer,keywords,explanation,...q})=>q)});}
if(path==='interview/token'){if(!user)return json({error:'Please sign in to start a live interview.'},401);if(!config('ASSEMBLYAI_API_KEY'))return json({error:'AssemblyAI API key is missing. Add ASSEMBLYAI_API_KEY to use AI Interviewer.'},503);const context=z.object({type:z.enum(interviewTypes),topic:z.string().trim().min(2).max(100),difficulty:z.enum(interviewDifficulties),questionCount:z.union([z.literal(5),z.literal(10),z.literal(15)]),language:z.enum(interviewLanguages),weakTopics:z.array(z.string().trim().min(1).max(100)).max(10).optional()}).parse(await req.json());const r=await fetch('https://agents.assemblyai.com/v1/token?expires_in_seconds=60&max_session_duration_seconds=1800',{headers:{Authorization:config('ASSEMBLYAI_API_KEY')},signal:AbortSignal.timeout(15000)});if(!r.ok)return json({error:r.status===401||r.status===403?'AssemblyAI rejected the API key or Voice Agent access. Check your key and account access.':r.status===429?'AssemblyAI usage limit reached. Check credits or try again later.':'AssemblyAI could not connect. Please retry.'},r.status===429?429:502);const d=await r.json() as {token:string};if(!d.token)throw new Error('AssemblyAI did not return a temporary token.');return json({token:d.token,...interviewSession(context)});}
if(path==='voice/token'){if(!user)return json({error:'Please sign in to start live voice.'},401);if(!config('ASSEMBLYAI_API_KEY'))return json({error:'AssemblyAI API key is missing. Add ASSEMBLYAI_API_KEY in Site settings, then republish.'},503);const context=z.object({subject:z.string().max(60).optional(),topic:z.string().max(100).optional(),learningMode:z.enum(['General Tutor','Explain and Learn','Quiz Mode','Revision Mode']).optional(),level:z.enum(['Beginner','Intermediate','Advanced']),language:z.enum(['English','Urdu','Urdu-English'])}).parse(await req.json());const r=await fetch('https://agents.assemblyai.com/v1/token?expires_in_seconds=60&max_session_duration_seconds=900',{headers:{Authorization:config('ASSEMBLYAI_API_KEY')},signal:AbortSignal.timeout(15000)});if(!r.ok)return json({error:r.status===401||r.status===403?'AssemblyAI rejected the API key or Voice Agent access. Check your key and account access.':r.status===429?'AssemblyAI usage limit reached. Check credits or try again later.':'AssemblyAI could not connect. Please retry.'},r.status===429?429:502);const d=await r.json() as {token:string};if(!d.token)throw new Error('AssemblyAI did not return a temporary token.');return json({token:d.token,session:voiceSession(context)});}
if(path==='voice/session')return json({id:crypto.randomUUID(),mode:'live'});
if(path==='voice/end')return json({success:true});
if(path==='voice/transcribe'){if(!config('ASSEMBLYAI_API_KEY'))return json({error:'AssemblyAI is not configured. Add ASSEMBLYAI_API_KEY in Site settings.'},503);const data=await req.formData();const file=data.get('audio');if(!(file instanceof File)||file.size>8*1024*1024||!file.type.startsWith('audio/'))return json({error:'Provide an audio recording smaller than 8 MB.'},400);const headers={authorization:config('ASSEMBLYAI_API_KEY')};const upload=await fetch('https://api.assemblyai.com/v2/upload',{method:'POST',headers,body:file,signal:AbortSignal.timeout(30000)});if(!upload.ok)throw new Error('Audio upload failed. Please try again.');const u=await upload.json() as any;const r=await fetch('https://api.assemblyai.com/v2/transcript',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({audio_url:u.upload_url,speech_models:['universal-3-pro','universal-2'],language_detection:true}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Transcription could not start. Please try text input.');const result=await r.json() as any;
// Bind polling authorization to a signed, short-lived cookie so another student cannot retrieve an arbitrary transcript.
const value=await sign(result.id+'|'+user!.id);return json({id:result.id},200,{'Set-Cookie':`edu_transcript=${result.id}.${value}; HttpOnly; Secure; SameSite=Strict; Path=/api/voice; Max-Age=300`});}
if(path.startsWith('voice/transcript/')){const id=path.split('/')[2];if(!/^[a-zA-Z0-9-]+$/.test(id))return json({error:'Invalid transcript.'},400);const stored=req.headers.get('cookie')?.split('; ').find(x=>x.startsWith('edu_transcript='))?.slice(15);if(!user||stored!==id+'.'+await sign(id+'|'+user.id))return json({error:'This recording is not available in your session.'},403);const r=await fetch('https://api.assemblyai.com/v2/transcript/'+id,{headers:{authorization:config('ASSEMBLYAI_API_KEY')},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Unable to retrieve transcription.');const d=await r.json() as any;if(d.status==='completed')await fetch('https://api.assemblyai.com/v2/transcript/'+id,{method:'DELETE',headers:{authorization:config('ASSEMBLYAI_API_KEY')}});return json({status:d.status,text:d.text,error:d.status==='error'?'The recording could not be transcribed. Please try again.':undefined});}
return json({error:'Endpoint not found.'},404);
}catch(e){return json({error:e instanceof z.ZodError?'Please check the submitted fields.':e instanceof Error?e.message:'Something went wrong. Please retry.'},400)}}
async function sign(value:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(config('ASSEMBLYAI_API_KEY')),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export const GET=handle;export const POST=handle;export const PATCH=handle;
